### ISSUE TITLE
Cannot read properties of undefined (reading 'style')

### ISSUE THREAD

**Issue by xuguanqun** [fengyuanchen/viewerjs#549]
```
viewer.view(0);
```
```
Uncaught TypeError: Cannot read properties of undefined (reading 'style')
    at Viewer.open (viewer.js:3072:1)
    at Viewer.show (viewer.js:1850:1)
    at Viewer.view (viewer.js:1991:1)
    at index.tsx:132:1
    at commitHookEffectListMount (react-dom.development.js:23049:1)
    at commitPassiveMountOnFiber (react-dom.development.js:24816:1)
    at commitPassiveMountEffects_complete (react-dom.development.js:24781:1)
    at commitPassiveMountEffects_begin (react-dom.development.js:24768:1)
    at commitPassiveMountEffects (react-dom.development.js:24756:1)
    at flushPassiveEffectsImpl (react-dom.development.js:26990:1)
```

**Comment by fengyuanchen** [comment]
Please read the note about using methods: https://github.com/fengyuanchen/viewerjs#methods
